// <auto-generated />
namespace MolDavaBanking.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ChangeTransationsTableStructure_AddTransactionNumberField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeTransationsTableStructure_AddTransactionNumberField));
        
        string IMigrationMetadata.Id
        {
            get { return "201905081313268_ChangeTransationsTableStructure_AddTransactionNumberField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
